GRANT CONNECT ON DATABASE fits TO fits_w;
GRANT USAGE ON SCHEMA fits TO fits_w;
GRANT ALL ON ALL TABLES IN SCHEMA fits TO fits_w;
GRANT ALL ON ALL SEQUENCES IN SCHEMA fits TO fits_w;

GRANT CONNECT ON DATABASE fits TO fits_r;
GRANT USAGE ON SCHEMA fits TO fits_r;
GRANT SELECT ON ALL TABLES IN SCHEMA fits TO fits_r;