name: fits
on:
  push: {}
  release:
    types: [published]
  workflow_dispatch: {}
permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write
env:
  FOLDER: ./cmd ./dapper
  # doesn't have an ECR by that name; EXCLUDE is regex and is '|' separated (e.g: a|b|c)
  EXCLUDE: '\?\?\?|dapper-send-test'
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      git-rev: ${{ steps.git-rev.outputs.git-rev }}
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: git-rev
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          echo "git-rev=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - id: set
        run: |
          echo "matrix=$(grep -r 'package main' | sort | cut -d ':' -f1 | grep -Ewv "$EXCLUDE" - | grep '.go$' | xargs -n 1 dirname | sort | uniq | grep -v vendor | xargs -i echo './{}' | xargs | yq 'split(" ")|.[]|. as $folder |split("/") | {"target":.[-1],"folder":$folder,"sourcepath":"."} | (select(.folder|contains("dapper"))|.sourcepath)="./dapper"' -ojson | jq -rcM -s '{"include":.}')" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          jq . <<< '${{ steps.set.outputs.matrix }}'
  build-app:
    uses: GeoNet/Actions/.github/workflows/reusable-go-apps.yml@main
    with:
      paths: |
        ./cmd/...
      buildSetup: |
        sudo apt-get update
        sudo apt-get install -y xsltproc
      testSetup: |
        sudo apt-get -yq update
        sudo apt-get install -y xsltproc
        docker \
          run -d \
          -p 5432:5432 \
          -e POSTGRES_PASSWORD=test \
          -e POSTGRES_USER=fits_w \
          -e POSTGRES_DB=fits \
          --name postgres \
          docker.io/postgis/postgis:15-3.3-alpine
        echo "Waiting until Postgres is ready..."
        until nc -zv -w 1 127.0.0.1 5432; do
        sleep 1s
        done
        sleep 5s
        docker logs postgres
        echo "Postgres is ready"
        psql postgresql://fits_w:test@127.0.0.1/fits --file=./etc/ddl/drop-create-users.ddl
        psql postgresql://fits_w:test@127.0.0.1/fits --file=./etc/ddl/create-db.ddl
        psql postgresql://fits_w:test@127.0.0.1/fits --file=./etc/ddl/fits-create.ddl
        psql postgresql://fits_w:test@127.0.0.1/fits --file=./etc/ddl/fits-functions.ddl
        psql postgresql://fits_w:test@127.0.0.1/fits --file=./etc/ddl/user-permissions.ddl
        psql postgresql://fits_w:test@127.0.0.1/fits --file=./etc/ddl/fits-test-data.ddl
  go-build-dapper:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) && startsWith(github.repository, 'GeoNet/') != false }}
    uses: GeoNet/Actions/.github/workflows/reusable-go-build-smoke-test.yml@main
    with:
      working-directory: ./dapper
      paths: |
        ./cmd/...
      setup: |
        sudo apt-get update
        sudo apt-get install -y xsltproc
  build:
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    uses: GeoNet/Actions/.github/workflows/reusable-docker-build.yml@main
    with:
      setup: |
        # this is an anti-pattern
        mkdir -p "${{ fromJSON(toJSON(matrix)).folder }}/assets"
        DOCKERFILE="${{ fromJSON(toJSON(matrix)).folder }}/${{ fromJSON(toJSON(matrix)).target }}.Dockerfile"
        if [ -f "${{ fromJSON(toJSON(matrix)).folder }}/Dockerfile" ]; then
          echo "using existing"
          cp "${{ fromJSON(toJSON(matrix)).folder }}/Dockerfile" "$DOCKERFILE"
        else
          echo "copy-editing template"
          cp ./Dockerfile_template "$DOCKERFILE"
          cat << EOF >> "$DOCKERFILE"
        CMD ["/${{ fromJSON(toJSON(matrix)).target }}"]
        EOF
        fi
      context: .
      buildArgs: |
        BUILD=${{ fromJSON(toJSON(matrix)).target }}
        GIT_COMMIT_SHA=${{ needs.prepare.outputs.git-rev }}
        VERSION=git-${{ needs.prepare.outputs.git-rev }}
        ASSET_DIR=${{ fromJSON(toJSON(matrix)).folder }}/assets
        SOURCEPATH=${{ fromJSON(toJSON(matrix)).sourcepath }}
      dockerfile: ${{ fromJSON(toJSON(matrix)).folder }}/${{ fromJSON(toJSON(matrix)).target }}.Dockerfile
      imageName: ${{ fromJSON(toJSON(matrix)).target }}
      platforms: linux/amd64
      push: ${{ github.ref == 'refs/heads/main' }}
      tags: latest,git-${{ needs.prepare.outputs.git-rev }}
      registryOverride: 862640294325.dkr.ecr.ap-southeast-2.amazonaws.com
      aws-region: ap-southeast-2
      aws-role-arn-to-assume: arn:aws:iam::862640294325:role/github-actions-geonet-ecr-push
      aws-role-duration-seconds: "3600"
